### ISSUE TITLE
upgrade for node 16 and other deprecations

### ISSUE THREAD

**Issue by brainfoolong** [jwalton/gh-docker-logs#16]
Hi!

Since a while, node12 is deprecated in git actions.

    Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:  jwalton/gh-docker-logs

Can you please release a new version that fixes this?

You also should upgrade the core action dependency to 1.10.0 or greather.

See GitHub blogs about that.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Thank you.

**Comment by brainfoolong** [comment]
Holy moly, that was fast :) thank you

**Comment by jwalton** [comment]
Someone just raised the same issue in [gh-find-current-pr](https://github.com/jwalton/gh-find-current-pr/issues/25) so I was already working on it.  :)
